---
# Ansible Version: 2.9
- hosts: vmware
  vars_files:
    - vars.yml
  tasks:
    - name: Create a virtual machine
      # https://docs.ansible.com/ansible/2.9/modules/vmware_guest_module.html#parameters
      vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        folder: /DC1/vm/
        name: testmachine01
        state: poweredon
        guest_id: testmachine01
        esxi_hostname: "{{ esxi_hostname }}"
        disk:
          - size_gb: 100
            type: thin
            datastore: datastore1
        hardware:
          memory_mb: 16384
          num_cpus: 4
          scsi: paravirtual
        networks:
          - name: VM Network
            mac: aa:bb:dd:aa:00:14
            ip: 10.10.10.100
            netmask: 255.255.255.0
            device_type: vmxnet3
        wait_for_ip_address: true
        wait_for_ip_address_timeout: 600
      delegate_to: localhost
      register: deploy_vm
